spring.application.name=backend
spring.data.mongodb.uri=mongodb://localhost:27017/complaint_system
mongodb+srv://sajingrace04_db_user:<db_password>@cms-cluster.hxdzy7d.mongodb.net/?appName=cms-cluster
server.port=8080
